# Generated by Django 5.2.7 on 2025-10-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=10)),
                ('desarrollador', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=10)),
                ('plataforma', models.CharField(max_length=50)),
                ('fecha_lanzamiento', models.CharField(max_length=50)),
            ],
        ),
    ]
